<?php
/**
 * Created by PhpStorm.
 * User: Антон
 * Date: 20.01.2018
 * Time: 12:16
 */

namespace backend\modules\user\models;


use common\models\db\City;
use common\models\db\Country;
use common\models\db\HigherEducation;

class HigherEducationForm extends HigherEducation
{
    public $country_id;
    public $city_id;


    public function rules()
    {
        return array_merge(parent::rules(), [
            [['country_id'], 'exist', 'skipOnError' => true, 'targetClass' => Country::className(), 'targetAttribute' => ['country_id' => 'id']],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => City::className(), 'targetAttribute' => ['city_id' => 'id']],
        ]);
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'city_id' => \Yii::t('app', 'City ID'),
            'country_id' => \Yii::t('app', 'Country ID')
        ]); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->country_id = $this->place->city->country_id;
        $this->city_id = $this->place->city_id;
        parent::afterFind();
    }

}