<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "profile".
 *
 * @property integer $user_id
 * @property string $name
 * @property string $public_email
 * @property string $gravatar_email
 * @property string $gravatar_id
 * @property string $location
 * @property string $website
 * @property string $bio
 * @property string $timezone
 * @property string $last_name
 * @property string $gender
 *
 * @property User $user
 */
class Profile extends \dektrium\user\models\Profile
{
    public function getUser()
    {
        return parent::getUser(); // TODO: Change the autogenerated stub
    }
}
