<?php
/**
 * Created by PhpStorm.
 * User: Антон
 * Date: 23.12.2017
 * Time: 10:53
 */

namespace common\models\db;


class PostLikes extends \common\models\PostLikes
{
    const TYPE_LIKE  = 1;
    const TYPE_DISLIKE = 0;

    public function beforeValidate()
    {
        if(!\Yii::$app->user->isGuest && empty($this->user_id)){
            $this->user_id = \Yii::$app->user->id;
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}