<?php
/**
 * Created by PhpStorm.
 * User: Антон
 * Date: 23.12.2017
 * Time: 10:55
 */

namespace common\models\db;


use yii\db\Expression;

class PostViews extends \common\models\PostViews
{
    private $_user_ip;

    public function __construct(array $config = [])
    {
        $this->_user_ip = \Yii::$app->request->userIP;
        parent::__construct($config);
    }

    public function beforeValidate()
    {
        $this->ip_address = new Expression("INET_ATON($this->_user_ip)");
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}