<?php
/**
 * Created by PhpStorm.
 * User: Антон
 * Date: 23.12.2017
 * Time: 10:55
 */

namespace common\models\db;

class PostViews extends \common\models\PostViews
{
    public function beforeValidate()
    {
        $this->ip_address = ip2long('123.12.12.12'/*\Yii::$app->request->userIP*/);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->ip_address = long2ip($this->ip_address);
    }
}